### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by SikoticVinyl** [SikoticVinyl/TheCrazyPasswordGen#2]
Build out the generatePassword function in the JS File

The function must have options that are selectable for:
How many characters? (Between 8 and 128)
Caps or No caps?
Special Characters?
Numbers?

Once password is generated it needs to be displayed in either an alert or written to the page.

**Comment by SikoticVinyl** [comment]
GIVEN I need a new, secure password
WHEN I click the button to generate a password
THEN I am presented with a series of prompts for password criteria
WHEN prompted for password criteria
THEN I select which criteria to include in the password
WHEN prompted for the length of the password
THEN I choose a length of at least 8 characters and no more than 128 characters
WHEN asked for character types to include in the password
THEN I confirm whether or not to include lowercase, uppercase, numeric, and/or special characters
WHEN I answer each prompt
THEN my input should be validated and at least one character type should be selected
WHEN all prompts are answered
THEN a password is generated that matches the selected criteria
WHEN the password is generated
THEN the password is either displayed in an alert or written to the page

**Comment by RawaneG** [comment]
Hey ! I've made a password Generator and it accessible on my repositories, Feel free to check if it matches with your requirements. 
https://github.com/RawaneG/TP-Javascript/tree/master/TP%203

**Comment by SikoticVinyl** [comment]
Completed Javascript coding, created randomized password based on user input.
